### ISSUE TITLE
工程依赖问题

### ISSUE THREAD

**Issue by yangming860101** [ctripcorp/x-pipe#184]
导入eclipse发现有些组件依赖携程内部工程，比如parent依赖：
<parent>
		<groupId>com.ctrip.framework</groupId>
		<artifactId>framework-parent</artifactId>
		<version>1.3.0</version>
	</parent>

还有cat-client，foundation-service等，这些依赖问题怎么解决？

**Comment by wenchaomeng** [comment]
切换到分支：mvn_repo，里面的jar包即携程相关的依赖
然后将这些jar包拷贝到本地mvn仓库
