### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by rfyiamcool** [ctripcorp/x-pipe#205]
两个机房的keeper数量是对等的么？ 
 x-pipe 支持 两个机房都是redis cluster？

期待你的回复.

**Comment by rfyiamcool** [comment]
不能相互复制吧，全网只能有一个idc是写的 ？

**Comment by rfyiamcool** [comment]
两个机房都需要配置MetaServer ?  那Meta的数据同步又怎么搞？  没想明白这一点。

**Comment by wenchaomeng** [comment]
只有一个机房是可写，另外一个机房只读；
meta server数据不需要同步，两个机房数据本身就不同，每个meta server集群获取本机房内数据，挂你机房内keeper、redis状态；

**Comment by rfyiamcool** [comment]
明白.  感谢
