### ISSUE TITLE
如果只需要keeper（且keeper不需要高可用），要怎么打包安装

### ISSUE THREAD

**Issue by bylijinnan** [ctripcorp/x-pipe#206]
我们在寻求两个redis cluster集群之间的数据同步方案；对keeper的高可用没有要求。
keeper可以独立部署吗？

**Comment by wenchaomeng** [comment]
可以的
com.ctrip.xpipe.redis.keeper.container.KeeperContainerController提供rest接口可以增删keeper

**Comment by wenchaomeng** [comment]
add Keeper后，通过redis-cli发送命令可以控制keeper连接到redis：
> keeper setstate ACTIVE 127.0.0.1 6379
