### ISSUE TITLE
maven依赖问题

### ISSUE THREAD

**Issue by bylijinnan** [ctripcorp/x-pipe#207]
从mvn_repo分支下载了必要的jar包，编译打包仍然报错。

编译x-pipe时，提示缺少包：
Failure to find org.unidal.framework:foundation-service:jar:3.1.2

下载了org.unidal.framework编译，又提示：
Failure to find org.unidal.maven.plugins:codegen-maven-plugin:jar:3.0.2

可否对依赖作一下整理？谢谢

**Comment by bylijinnan** [comment]
自己手动把所有依赖都install到本地库了：
https://github.com/bylijinnan/x-pipe/commit/70ede363bc50ab47296b4bfbc0c44255de3d891a

**Comment by NickNYU** [comment]
@bylijinnan 之前有过一次版本升级，相关的maven依赖会有缺失，这个bug已经修复，现在不用拉到本地也可，前提是跟github的网络连接没问题

谢谢
