### ISSUE TITLE
predis 与x-pipe的兼容使用

### ISSUE THREAD

**Issue by simpson9527** [ctripcorp/x-pipe#210]
我们现在业务都是使用predis连接redis，predis自实现了读写分离功能，默认把读请求发给所有slave。那么通过keeper做跨机房主从复制，线上客户端的请求会打到容灾机房吗？，因为一般线下环境的机房和容灾机房在物理距离上比较远，网络延迟自然比较大（我们线上到容灾的网络延迟是25ms左右），如果线上客户端的读请求打到容灾，会把整个缓存数据读取拖垮。

**Comment by NickNYU** [comment]
需要一些详细的信息，比如 predis把请求发送给所有slave的操作是怎样的？predis是怎么知道所有的slave的，通过info replication？

我觉得你的问题更多的是predis是如何工作的，而不是xpipe复制数据会不会对读有影响
