### ISSUE TITLE
缺少pom文件

### ISSUE THREAD

**Issue by gaoyulin** [ctripcorp/x-pipe#244]
缺少这个pom文件 
<parent>
        <groupId>com.ctrip.framework</groupId>
        <artifactId>framework-parent</artifactId>
        <version>1.5.0</version>
    </parent>

**Comment by NickNYU** [comment]
参考 wiki 中的配置, 将 git branch 切换到 mvn_repo, 缺少的依赖在里面

**Comment by NickNYU** [comment]
没有问题的话, 我就先关掉这个 case 了
