### ISSUE TITLE
备机房的sentinel怎么启动，怎么管理

### ISSUE THREAD

**Issue by mengmeixiyi015** [ctripcorp/x-pipe#259]

**Comment by NickNYU** [comment]
XPipe 中哨兵信息只是配置项, 真实的哨兵需要用户自己启动
对于哨兵的管理, XPipe 的 console 组件中有监控功能, 能够保证 哨兵对应不同 redis 组的监控和配置是一致的
哨兵本身的启停, 需要用户自己维护

**Comment by mengmeixiyi015** [comment]
正常情况下，从数据中心的sentinel需要启动吗？如果需要启动的话monitor mymaster ip，ip是主数据中心的master还是从数据中心的keeper，还是其他？

**Comment by NickNYU** [comment]
sentinel 需要保持启动的状态, 当然, 你不启动也不会影响切换

哨兵只需启动即可, xpipe 会根据配置自动管理, 包括添加/删除/RESET

**Comment by mengmeixiyi015** [comment]
从数据中心的sentinel需要启动，但是monitor mymaster ip不在文件里面配置？而是在console或者直接操作数据库配置？是这个意思吗？

**Comment by chengzile** [comment]
> 从数据中心的sentinel需要启动，但是monitor mymaster ip不在文件里面配置？而是在console或者直接操作数据库配置？是这个意思吗？

从数据的哨兵没有配置monitor mymaster ip ，从console看redis状态显示X，请问你后面如何配置的
