### ISSUE TITLE
centos7上编译x-pipe失败

### ISSUE THREAD

**Issue by zouzc** [ctripcorp/x-pipe#266]
编译步骤: 1.下载源码 2.git checkout mvn_repo 3. sh install.sh    4. git checkout master  5. mvn install -DskipTests

错误信息如下:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (framework-parent-check) on project xpipe-parent: Execution framework-parent-check of goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce failed: org.apache.maven.shared.dependency.graph.DependencyGraphBuilderException: Could not resolve dependencies for project com.ctrip.framework.xpipe:xpipe-parent:pom:1.1.0-SNAPSHOT: Failed to collect dependencies at com.dianping.cat:cat-client:jar:2.21.4: Failed to read artifact descriptor for com.dianping.cat:cat-client:jar:2.21.4: Could not find artifact com.ctrip.framework:framework-bom:pom:2.25.0 in central (http://repo1.maven.org/maven2) -> [Help 1]

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (framework-parent-check) on project xpipe-parent: Execution framework-parent-check of goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce failed: org.apache.maven.shared.dependency.graph.DependencyGraphBuilderException: Could not resolve dependencies for project com.ctrip.framework.xpipe:xpipe-parent:pom:1.1.0-SNAPSHOT: Failed to collect dependencies at com.dianping.cat:cat-client:jar:2.21.4

cat ~/.m2/repository/com/ctrip/framework/framework-bom/2.25.0/framework-bom-2.25.0.pom.lastUpdated
#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Tue May 28 10:43:19 CST 2019
http\://repo1.maven.org/maven2/.error=
http\://repo1.maven.org/maven2/.lastUpdated=1559011399847

**Comment by NickNYU** [comment]
现在可以了, 需要 Git pull 一次
之前因为升级 cat 的版本导致依赖问题
还有编译的话, 应该是
`mvn clean install -Ppackage,local -DskipTests`
详请参考 X-Pipe 的 github wiki 页面的安装步骤

**Comment by zouzc** [comment]
git pull后使用 mvn clean install -Ppackage,local -DskipTests, 在编译redis-integration-test失败,错误信息:[ERROR] Failed to execute goal on project redis-integration-test: Could not resolve dependencies for project com.ctrip.framework.xpipe.redis:redis-integration-test:jar:1.1.0-SNAPSHOT: Could not find artifact org.unidal.framework:test-framework:jar:2.5.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by NickNYU** [comment]
这个依赖是有的, 你看
https://github.com/ctripcorp/x-pipe/tree/mvn_repo/org/unidal/framework/test-framework/2.5.0
这个链接是有的

建议去本地 maven 仓库看一下, 是否相关依赖没有 copy 进去?

**Comment by zouzc** [comment]
ll ~/.m2/repository/org/unidal/framework/test-framework/2.5.0
total 8
-rw-r--r-- 1 root root 244 May 28 14:21 test-framework-2.5.0.jar.lastUpdated
-rw-r--r-- 1 root root 244 May 28 14:21 test-framework-2.5.0.pom.lastUpdated


本地仓库中跟上面链接中差别挺大的，需要复制哪几个文件? 本地仓库是用git mvn_repo的install.sh生成的，好像跟链接的有出入。
test-framework-2.5.0-sources.jar 	revert to previous version 	2 years ago
	test-framework-2.5.0-sources.jar.sha1 	revert to previous version 	2 years ago
	test-framework-2.5.0.jar 	revert to previous version 	2 years ago
	test-framework-2.5.0.jar.sha1 	revert to previous version 	2 years ago
	test-framework-2.5.0.pom 	revert to previous version 	2 years ago
	test-framework-2.5.0.pom.lastUpdated 	revert to previous version 	2 years ago
	test-framework-2.5.0.pom.sha1 	revert to previous version 	2 years ago

**Comment by NickNYU** [comment]
mvn_repo 全部需要复制, 先清空本地 mvn 仓库

**Comment by zouzc** [comment]
“mvn_repo 全部需要复制, 先清空本地 mvn 仓库” 复制是执行sh install.sh 自动做的? 还是要手工cp mvn_repo/com和 mvn_repo/org到本地仓库的对应目录下

**Comment by zouzc** [comment]
在mvn_repo的install.sh 中增加如下，test-framework 编译成功
for _Version in `ls org/unidal/framework/test-framework`; do
	mvn install:install-file -Dfile=org/unidal/framework/test-framework/$_Version/test-framework-$_Version.jar -DpomFile=org/unidal/framework/test-framework/$_Version/test-framework-$_Version.pom
done

**Comment by zhaizhifen** [comment]
Ubuntu 16.04.1 LTS
Linux VM-0-4-ubuntu 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

## 创建目录
# mkdir -pv /apps/software/src
# cd /apps/software/src

## 将x-pipe的mvn_repo分支下载并安装依赖到本地maven库
# mkdir mvn_repo && cd mvn_repo
# git clone -b mvn_repo https://github.com/ctripcorp/x-pipe
# cd x-pipe
# vim install.sh 
## 添加以下内容到脚本末尾
for _Version in `ls org/unidal/framework/test-framework`; do
        mvn install:install-file -Dfile=org/unidal/framework/test-framework/$_Version/test-framework-$_Version.jar -DpomFile=org/unidal/framework/test-framework/$_Version/test-framework-$_Version.pom
done
# sh install.sh

## 安装完成后，下载x-pipe源码编译
# cd /apps/software/src	
# git clone https://github.com/ctripcorp/x-pipe
# cd x-pipe
# mvn clean install -Plocal,package -DskipTests

## 最后输出
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] xpipe-parent ....................................... SUCCESS [01:34 min]
[INFO] core ............................................... SUCCESS [03:14 min]
[INFO] redis-parent ....................................... SUCCESS [  0.023 s]
[INFO] redis-core ......................................... SUCCESS [ 28.391 s]
[INFO] redis-keeper ....................................... SUCCESS [  1.497 s]
[INFO] redis-meta ......................................... SUCCESS [ 15.673 s]
[INFO] redis-console ...................................... SUCCESS [ 28.086 s]
[INFO] redis-integration-test ............................. SUCCESS [ 24.304 s]
[INFO] redis-proxy ........................................ SUCCESS [01:18 min]
[INFO] services ........................................... SUCCESS [  0.010 s]
[INFO] local-service ...................................... SUCCESS [  0.387 s]
[INFO] package ............................................ SUCCESS [  0.017 s]
[INFO] redis-meta-package ................................. SUCCESS [01:11 min]
[INFO] redis-keeper-package ............................... SUCCESS [  2.451 s]
[INFO] redis-console-package .............................. SUCCESS [  2.401 s]
[INFO] redis-proxy-package ................................ SUCCESS [  3.033 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:11 min
[INFO] Finished at: 2019-08-08T10:33:18+08:00
[INFO] Final Memory: 131M/497M
[INFO] ------------------------------------------------------------------------

**Comment by NickNYU** [comment]
可以提一个 PR 给我们
