### ISSUE TITLE
xpipe 1.10版本自动将哨兵的quorum设置为3，并且将宕机master删除,导致重启后无法跟新master建立主从关系

### ISSUE THREAD

**Issue by zouzc** [ctripcorp/x-pipe#269]
使用官网上的1.00二进制文件测试，在一台主机上模拟两个机房，并且每个机房部署了3个哨兵，手工将主机房的哨兵的quorum设置为2，过一会儿发现配置文件重新设置为3；将master redis杀死后，slave 能提升为master,但哨兵配置文件和新master中都将宕机master给删除了;宕机master重新启动后，无法与新master建立主从关系. 已知config_tbl中sentinel.auto.process 为true.

当其它一个哨兵宕机后，无法进行故障转移。

**Comment by wenchaomeng** [comment]
1：生产环境建议部署5个哨兵
2：master重新启动后，无法与心得master建立master-slave的问题目前模拟不出来；建议重新模拟一下，如果还有问题，附件贴一下哨兵日志

**Comment by zouzc** [comment]
测试环境部署了3个哨兵，并修改console的配置文件console.sentinel.quorum = {"total":3,"quorum":2}，
1.模拟一个哨兵宕机;
2.在10:22:24将6579(master)关闭, 2个哨兵将6679(slave)提升为master;
3.发生切换后，哨兵有将近2分多钟监视的master不对，依然是旧master,且没有感知到其它哨兵;
4. 在10:39:34.930将原master(6579)重启，发现哨兵不再监视新master(6679)，转而监视原master(6579)，后续哨兵中没有再打印日志。 原master(6579)不与新master(6679)建立主从关系,并且哨兵监视对象也不对。

###  哨兵进行故障转移 
23317:X 11 Jun 10:22:54.294 # +sdown master s2 172.11.15.162 6579
23317:X 11 Jun 10:22:54.350 # +odown master s2 172.11.15.162 6579 #quorum 2/2
23317:X 11 Jun 10:22:54.350 # +new-epoch 7
23317:X 11 Jun 10:22:54.351 # +try-failover master s2 172.11.15.162 6579
23317:X 11 Jun 10:22:54.395 # +vote-for-leader 8405a27e09988b04727c2d84123c809e72df49ca 7
23317:X 11 Jun 10:22:54.434 # e2a19372a635f770b48918b19195d39ae32b9398 voted for 8405a27e09988b04727c2d84123c809e72df49ca 7
23317:X 11 Jun 10:22:54.458 # +elected-leader master s2 172.11.15.162 6579
23317:X 11 Jun 10:22:54.458 # +failover-state-select-slave master s2 172.11.15.162 6579
23317:X 11 Jun 10:22:54.541 # +selected-slave slave 172.11.15.162:6679 172.11.15.162 6679 @ s2 172.11.15.162 6579
23317:X 11 Jun 10:22:54.541 * +failover-state-send-slaveof-noone slave 172.11.15.162:6679 172.11.15.162 6679 @ s2 172.11.15.162 6579
23317:X 11 Jun 10:22:54.632 * +failover-state-wait-promotion slave 172.11.15.162:6679 172.11.15.162 6679 @ s2 172.11.15.162 6579
23317:X 11 Jun 10:22:55.010 # +promoted-slave slave 172.11.15.162:6679 172.11.15.162 6679 @ s2 172.11.15.162 6579
23317:X 11 Jun 10:22:55.010 # +failover-state-reconf-slaves master s2 172.11.15.162 6579
23317:X 11 Jun 10:22:55.064 * +slave-reconf-sent slave 172.11.15.162:6100 172.11.15.162 6100 @ s2 172.11.15.162 6579
23317:X 11 Jun 10:22:55.461 * +slave-reconf-inprog slave 172.11.15.162:6100 172.11.15.162 6100 @ s2 172.11.15.162 6579
23317:X 11 Jun 10:22:55.461 * +slave-reconf-done slave 172.11.15.162:6100 172.11.15.162 6100 @ s2 172.11.15.162 6579
23317:X 11 Jun 10:22:55.531 # -odown master s2 172.11.15.162 6579
23317:X 11 Jun 10:22:55.531 # +failover-end master s2 172.11.15.162 6579
23317:X 11 Jun 10:22:55.531 # +switch-master s2 172.11.15.162 6579 172.11.15.162 6679
23317:X 11 Jun 10:22:55.531 * +slave slave 172.11.15.162:6100 172.11.15.162 6100 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:22:55.531 * +slave slave 172.11.15.162:6579 172.11.15.162 6579 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:23:25.597 # +sdown slave 172.11.15.162:6579 172.11.15.162 6579 @ s2 172.11.15.162 6679

###
23317:X 11 Jun 10:24:37.815 # -monitor master s2 172.11.15.162 6679
23317:X 11 Jun 10:24:39.422 # +monitor master s2 172.11.15.162 6579 quorum 2
23317:X 11 Jun 10:25:09.445 # +sdown master s2 172.11.15.162 6579


### 监控新master(6679)  从切换到此花费了将近5分钟
23317:X 11 Jun 10:27:06.961 # -monitor master s2 172.11.15.162 6579
23317:X 11 Jun 10:27:06.997 # +monitor master s2 172.11.15.162 6679 quorum 2
23317:X 11 Jun 10:27:07.034 * +slave slave 172.11.15.162:6100 172.11.15.162 6100 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:27:07.501 * +sentinel sentinel e2a19372a635f770b48918b19195d39ae32b9398 172.11.15.162 7001 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:29:37.822 # -monitor master s2 172.11.15.162 6679
23317:X 11 Jun 10:29:39.504 # +monitor master s2 172.11.15.162 6679 quorum 2
23317:X 11 Jun 10:29:39.584 * +slave slave 172.11.15.162:6100 172.11.15.162 6100 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:29:39.984 * +sentinel sentinel e2a19372a635f770b48918b19195d39ae32b9398 172.11.15.162 7001 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:32:05.278 # -monitor master s2 172.11.15.162 6679
23317:X 11 Jun 10:32:06.890 # +monitor master s2 172.11.15.162 6679 quorum 2
23317:X 11 Jun 10:32:06.892 * +slave slave 172.11.15.162:6100 172.11.15.162 6100 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:32:07.370 * +sentinel sentinel e2a19372a635f770b48918b19195d39ae32b9398 172.11.15.162 7001 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:34:37.826 # -monitor master s2 172.11.15.162 6679
23317:X 11 Jun 10:34:39.416 # +monitor master s2 172.11.15.162 6679 quorum 2
23317:X 11 Jun 10:34:39.432 * +slave slave 172.11.15.162:6100 172.11.15.162 6100 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:34:39.900 * +sentinel sentinel e2a19372a635f770b48918b19195d39ae32b9398 172.11.15.162 7001 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:37:05.282 # -monitor master s2 172.11.15.162 6679
23317:X 11 Jun 10:37:06.934 # +monitor master s2 172.11.15.162 6679 quorum 2
23317:X 11 Jun 10:37:06.967 * +slave slave 172.11.15.162:6100 172.11.15.162 6100 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:37:07.434 * +sentinel sentinel e2a19372a635f770b48918b19195d39ae32b9398 172.11.15.162 7001 @ s2 172.11.15.162 6679


23317:X 11 Jun 10:39:37.827 # -monitor master s2 172.11.15.162 6679
23317:X 11 Jun 10:39:39.422 # +monitor master s2 172.11.15.162 6679 quorum 2
23317:X 11 Jun 10:39:39.484 * +slave slave 172.11.15.162:6100 172.11.15.162 6100 @ s2 172.11.15.162 6679
23317:X 11 Jun 10:39:39.939 * +sentinel sentinel e2a19372a635f770b48918b19195d39ae32b9398 172.11.15.162 7001 @ s2 172.11.15.162 6679

### 哨兵监视对象变成了6579（原master)，不再监视6679（新master),后面没有哨兵日志了
23317:X 11 Jun 10:42:05.284 # -monitor master s2 172.11.15.162 6679
23317:X 11 Jun 10:42:06.855 # +monitor master s2 172.11.15.162 6579 quorum 2
23317:X 11 Jun 10:42:07.385 * +sentinel sentinel e2a19372a635f770b48918b19195d39ae32b9398 172.11.15.162 7001 @ s2 172.11.15.162 6579


### 5001，7001依然存活
root      3818  0.1  0.0 141888  2104 ?        Ssl  Jun10   2:12 redis-sentinel *:7000 [sentinel]
root      3877  0.1  0.0 141820  1928 ?        Ssl  Jun10   2:15 redis-sentinel *:8000 [sentinel]
root     15876  0.0  0.0 112712   984 pts/3    S+   11:18   0:00 grep --color=auto redis-senti
root     23317  0.2  0.0 141976  2384 ?        Ssl  09:56   0:14 redis-sentinel *:5001 [sentinel]

 redis-cli -p 5001 info Sentinel
# Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
sentinel_simulate_failure_flags:0
master0:name=s2,status=ok,address=172.11.15.162:6579,slaves=0,sentinels=2

**Comment by wenchaomeng** [comment]
将哨兵和Console日志一起打个包邮件到: wcmeng@ctrip.com

**Comment by zouzc** [comment]
@wenchaomeng  你好，日志已发送，请查收。谢谢

**Comment by wenchaomeng** [comment]
用户配置问题，哨兵地址配置为127.0.0.1:5000，redis配置为172.xxxx，不匹配。导致xpipe认为哨兵不存在，会进行哨兵删除、重新添加的操作。

哨兵地址配置为172.xxx后解决

**Comment by wenchaomeng** [comment]
用户配置问题，哨兵地址配置为127.0.0.1:5000，redis配置为172.xxxx，不匹配。导致xpipe认为哨兵不存在，会进行哨兵删除、重新添加的操作。

哨兵地址配置为172.xxx后解决
