### ISSUE TITLE
用这个框架客户端怎么连接？

### ISSUE THREAD

**Issue by travisgu** [ctripcorp/x-pipe#270]
客户端直接用jedis可以吗？如果可以的话怎么配置连接？
还是说一定需要ctrip的DAL客户端才可以。

**Comment by Pandoraemon** [comment]
同问.

**Comment by NickNYU** [comment]
@travisgu @Pandoraemon  可以直接用 jedis 链接
sharding 策略需要自己实现

我们后面会有排期做一个客户端出来, 目前暂时没有
