### ISSUE TITLE
xpipe创建集群是管理员邮箱必须是Ctrip.com结尾的

### ISSUE THREAD

**Issue by zouzc** [ctripcorp/x-pipe#272]
创建集群或者更新集群的管理员邮箱时，使用163或者其它结尾的报错，后台日志“[14:50:07:436][ERROR][http-nio-8080-exec-13][ConsoleDefaultExceptionHandler]Emails should be ctrip emails and separated by comma or semicolon,”  貌似代码中强制使用Ctrip.com.

xpipe的告警机制是怎样的，如何使用外部的邮箱/微信来接收告警

**Comment by NickNYU** [comment]
这个 bug 我在 [https://github.com/ctripcorp/x-pipe/commit/1784aea47b5ef2bf2f7d6489966d9e78d3f852a1](这个 commit) 修掉了

目前最新的打包还没有打进去, 你可以试试用最新的代码

**Comment by zouzc** [comment]
@NickNYU  好的，谢谢。我试下最新代码。请问下xpipe的告警机制是咋样的,需要部署什么组件。当监控的redis,keeper宕机时，xpipe以什么样的方式将告警信息发送给管理者

**Comment by NickNYU** [comment]
xpipe 的告警机制是通过实现 email 的 SPI 模块来实现的, xpipe 检查到有问题之后, 会调用发邮件的模块

这个模块是 SPI 的机制, 携程有自己的邮件系统

用户可以实现 "com.ctrip.xpipe.api.email.EmailService" 来收到邮件, 通过 maven 打包进去即可

具体开发模式在 service 中, 启用自己的 maven module, 然后在里面实现

打包的时候, 加上 -Ppackage,<自己的模块名字>

**Comment by zouzc** [comment]
了解了，谢谢。
