### ISSUE TITLE
什么情况下从库请求的offset会比keeper保存的offset要大呢？

### ISSUE THREAD

**Issue by MichaelScofield** [ctripcorp/x-pipe#274]
`PsyncHandler`[第92行](https://github.com/ctripcorp/x-pipe/blame/9fac96e7ba1db5db5b58c1d54f29f07d81a7fefa/redis/redis-keeper/src/main/java/com/ctrip/xpipe/redis/keeper/handler/PsyncHandler.java#L92)：
```
}else if(offsetRequest > endOffset +1){
```
从库要求的offset比keeper保存的offset还大，这是为什么呢，从库的同步速度不可能超过keeper同步主库的速度啊？

**Comment by NickNYU** [comment]
Keeper active 和 backup 切换的时候, 原有的 active 变为 backup, 开始向新的 active keeper 同步, 这个时候, 就有这个可能

**Comment by MichaelScofield** [comment]
多谢。除了这种主备切换的情况，有没有可能redis slave真正请求了更大的offset的情况呢？

**Comment by NickNYU** [comment]
对于 redis 的复制系统来说不可能, 这个你可以加我们的开源 QQ 群详细聊

**Comment by MichaelScofield** [comment]
好的，谢谢
