### ISSUE TITLE
如何添加redis密码配置

### ISSUE THREAD

**Issue by ONG-YA** [ctripcorp/x-pipe#279]
使用redis-3.2.1，该redis服务是设置了密码的，现启动metaserver的时候提示com.ctrip.xpipe.redis.core.protocal.error.RedisError: NOAUTH Authentication required，找不到哪里可以添加redis密码的

**Comment by NickNYU** [comment]
目前 xpipe 还没有支持密码, 可以自己进行改造

**Comment by ONG-YA** [comment]
> 目前 xpipe 还没有支持密码, 可以自己进行改造

哦哦，请教一下。。目前携程内部的redis是未设置密码还是有使用另外的方式处理了~

**Comment by NickNYU** [comment]
有密码加额外加密处理
