### ISSUE TITLE
redis状态问题

### ISSUE THREAD

**Issue by ONG-YA** [ctripcorp/x-pipe#281]
使用redis-4.0.11
安装包：redis-console-package-1.0.0.zip redis-keeper-package-1.0.0.zip 。。。
配置好redis信息后，界面上的状态一直是X，日志没发现在哪。。请问是哪里配置不对吗或者能否告诉下在哪可以看到错误信息。
ps.在机器上telnet redis端口那些 都是正常 ping也能正常返回pong
![image](https://user-images.githubusercontent.com/46466799/64416135-3a804700-d0c9-11e9-8e83-be573baa627a.png)

**Comment by NickNYU** [comment]
从 console 访问以下 redis, 就用你填写的IP,PORT, 看看是否是通的
一般都是这个问题

**Comment by ONG-YA** [comment]
> 用你填写的IP

访问过了是可以的，而且keeper我看到也加到redis了

**Comment by zouzc** [comment]
redis 2.8 同样遇到此问题，console所在主机能telnet redis, console日志中显示 "[DefaultDelayPingActionCollector][onInstanceStateChange]HealthCheckInstance{endpoint=redis://172.17.1.13:7000, lastPongTime=1569571350385, lastDelayTime=1569571349505, lastDelayNano=-2839321601536299}:InstanceSick".
 请问下console检测redis的原理是什么。

**Comment by NickNYU** [comment]
代码里面有具体内容, 可以参考 healthcheck 里面的内容
