### ISSUE TITLE
xpipe数据双向同步以及proxy问题

### ISSUE THREAD

**Issue by ONG-YA** [ctripcorp/x-pipe#284]
请教两个问题，
1、目前版本的xpipe是不是只是单向节点同步，也就是说只有一个master节点可以写入，另外一个节点只能读？
2、假设我们公司节点之间内网是可以通信的，是否不需要配置proxy，直接使用console、meta、keeper3个组件就行了？

**Comment by NickNYU** [comment]
1. 对的, 只是单向同步
2. 是的, 不用 proxy

**Comment by ONG-YA** [comment]
> 1. 对的, 只是单向同步
> 2. 是的, 不用 proxy

感谢
