### ISSUE TITLE
Failure to find com.ctrip.framework:framework-parent:pom:1.5.0

### ISSUE THREAD

**Issue by wenweihu86** [ctripcorp/x-pipe#317]
编译失败，缺少这个包，从哪里获取？

**Comment by NickNYU** [comment]
https://github.com/ctripcorp/x-pipe/wiki/QuickStart#%E4%BE%9D%E8%B5%96%E7%9A%84-maven-%E4%BB%93%E5%BA%93-jar-%E5%8C%85%E4%BD%8D%E7%BD%AE

**Comment by wenweihu86** [comment]
试了下，这个库还是找不到，org.unidal.framework:test-framework:pom:2.5.0

**Comment by copyshop** [comment]
install.sh 脚本里面加上test-framework 就行了    我和你一样   看下install脚本里面好像把test-framework  漏掉了   里面好多依赖的是他们内部的类库  确实难受

**Comment by copyshop** [comment]
> 试了下，这个库还是找不到，org.unidal.framework:test-framework:pom:2.5.0

install.sh 脚本里面加上test-framework 就行了 我和你一样 看下install脚本里面好像把test-framework 漏掉了 里面好多依赖的是他们内部的类库 确实难受

**Comment by NickNYU** [comment]
多谢 @copyshop 提醒, 我增加了关于org.unidal.framework:test-framework:pom:2.5.0 在 install.sh 的脚本中安装步骤
