### ISSUE TITLE
failed to build from source code

### ISSUE THREAD

**Issue by kapsterio** [ctripcorp/x-pipe#358]
[INFO] xpipe-parent ....................................... SUCCESS [  0.885 s]
[INFO] core ............................................... FAILURE [  3.909 s]
[INFO] redis-parent ....................................... SKIPPED
[INFO] redis-core ......................................... SKIPPED
[INFO] redis-keeper ....................................... SKIPPED
[INFO] redis-meta ......................................... SKIPPED
[INFO] redis-console ...................................... SKIPPED
[INFO] redis-integration-test ............................. SKIPPED
[INFO] redis-proxy ........................................ SKIPPED
[INFO] services ........................................... SKIPPED
[INFO] local-service ...................................... SKIPPED
[INFO] package ............................................ SKIPPED
[INFO] redis-meta-package ................................. SKIPPED
[INFO] redis-keeper-package ............................... SKIPPED
[INFO] redis-console-package .............................. SKIPPED
[INFO] redis-proxy-package ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.001 s
[INFO] Finished at: 2020-05-11T17:41:13+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:testCompile (default-testCompile) on project core: Compilation failure
[ERROR] /Users/johnny/x-pipe/core/src/test/java/com/ctrip/xpipe/testutils/SpringApplicationStarter.java:[4,34] package com.sun.javafx.collections does not exist

**Comment by NickNYU** [comment]
应该是 Java 版本问题, 目前 XPipe 使用的是 JDK8
这个依赖在 JDK9 或者 JDK11 以后, 可能会没有, 我看你提了 PR, 后面会在 PR 上讨论
这个 Issue 我先关了
