### ISSUE TITLE
请问支持redis5以上的版本吗？

### ISSUE THREAD

**Issue by tcrct** [ctripcorp/x-pipe#375]
请问支持redis5以上的版本吗？
另外，是否支持redis cluster集群模式吗？

**Comment by NickNYU** [comment]
支持 redis5 以上版本,  理论上也支持 redis6

集群模式不支持, 需要自己改造

**Comment by tcrct** [comment]
> 支持 redis5 以上版本, 理论上也支持 redis6
> 
> 集群模式不支持, 需要自己改造

谢谢回复，请问集群模式需要自己改造，能具体说一下方向吗？谢谢

**Comment by NickNYU** [comment]
具体方向没有, 主要还是基本 keeper 的改造, console/meta 可以后期改造
