### ISSUE TITLE
keeper将日志写磁盘以及断点续传逻辑能分享一下吗

### ISSUE THREAD

**Issue by luoming1224** [ctripcorp/x-pipe#379]
多个keeper各自写日志吗？如何保证日志文件一致？当数据中心之间的网络出现较长时间异常时进行断点续传，怎样从日志文件中找到续传的位置点？

**Comment by NickNYU** [comment]
这个推荐你研究一下 redis 是如何增量复制的, keeper 本身可以认为是一个 redis
