### ISSUE TITLE
表名大小写不统一，还是要严谨一点

### ISSUE THREAD

**Issue by SamZhangGo** [ctripcorp/x-pipe#381]
[15:54:47:386][ERROR][main][DefaultDcMetaCache][loadMetaManager][consoleService]
[response body:{
  "exception" : "com.ctrip.xpipe.redis.console.exception.ServerException",
  "message" : "Load data failed.Error when executing query(SELECT zonetbl.id,zonetbl.zone_name,zonetbl.DataChange_LastTime,zonetbl.deleted FROM zone_tbl zonetbl WHERE zonetbl.id = ?) failed, proto: ZoneTbl[data-change-last-time: null, deleted: false, id: 0, key-id: 1, zone-name: null], message: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'fxxpipe.zone_tbl' doesn't exist."
}] org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
![image](https://user-images.githubusercontent.com/2421429/96691612-adc14700-13b7-11eb-9451-47aeeeefe6dd.png)

**Comment by NickNYU** [comment]
多谢建议, 这个主要原因是 MySQL 默认是忽略大小写的

请问你是用了其他的 RDS 还是 MySQL, 如果是 MySQL 的话, 麻烦问下版本信息

谢谢

**Comment by SamZhangGo** [comment]
mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64) using  EditLine wrapper

**Comment by NickNYU** [comment]
谢谢, 这个 issue 我先关闭了
