### ISSUE TITLE
[Bugfix] Keeper - Redis loop replicating

### ISSUE THREAD

**Issue by NickNYU** [ctripcorp/x-pipe#382]
### Background
Backup Site
Active Keeper as a master of downstream Redis

### Steps
1. Keeper is syncing data to Redis while Redis delays
2. Keeper is set(by MetaServer) to be as slave of the Redis
3. Redis replies a full sync as keeper's offset is larger than itself
4. Keeper is set(by MetaServer) to be as slave of upstream active keeper, meanwhile, the Redis RDB file is not completely received.
5. Keeper asks psync to upstream keeper using incorrect offset received from Redis' full sync
6. Upstream keeper will consider downstream keeper(the issue one) as a valid partial sync, because offset is partial syncable.
7. Backup site Redis will never be able to get synced data, because keeper lack the command files between upstream keeper's RDB file's offset and the offset it sends to upstream asking for a partial sync

**Comment by wuchengcheng2016** [comment]
fixed
