### ISSUE TITLE
请问目前版本支持双向同步了吗

### ISSUE THREAD

**Issue by neo0591** [ctripcorp/x-pipe#432]
请问目前版本支持双向同步了吗，是否开源了？

**Comment by NickNYU** [comment]
双相同步支持，但是没开源

**Comment by levie-vans** [comment]
> 双相同步支持，但是没开源

还打算放出双向同步的开源版本吗？

**Comment by wenchaomeng** [comment]
已经放出来了，文档待补充，参考：
https://github.com/ctripcorp/xredis-crdt
https://github.com/ctripcorp/crdt-module

**Comment by neo0591** [comment]
非常感谢

**Comment by phyxdown** [comment]
@neo0591 start.sh应该能直接跑起来一组，本地测试，有问题的话@我

**Comment by patpatbear** [comment]
@neo0591  编译运行双向的文档已更新，供参考

**Comment by cwt9562** [comment]
> 已经放出来了，文档待补充，参考： https://github.com/ctripcorp/xredis-crdt https://github.com/ctripcorp/crdt-module

这个好像是让redis或xredis支持crdt吧？
有更多的说明嘛？

以及添加了crdt-module的redis，怎么和xpipe组合起来使用？

**Comment by wenchaomeng** [comment]
参考下：
https://github.com/ctripcorp/x-pipe/wiki/master-master-replication
