### ISSUE TITLE
Failed to collect dependencies at com.dianping.cat:cat-client:jar:3.3.18

### ISSUE THREAD

**Issue by help-lixin** [ctripcorp/x-pipe#444]
[ERROR] Failed to execute goal on project xpipe-parent: Could not resolve dependencies for project com.ctrip.framework.xpipe:xpipe-parent:pom:1.2.4: Failed to collect dependencies at com.dianping.cat:cat-client:jar:3.3.18: Failed to read artifact descriptor for com.dianping.cat:cat-client:jar:3.3.18: Could not transfer artifact org.unidal.framework:framework-bom:pom:4.0.0 from/to central (http://repo1.maven.org/maven2): Transfer failed for http://repo1.maven.org/maven2/org/unidal/framework/framework-bom/4.0.0/framework-bom-4.0.0.pom 501 HTTPS Required -> [Help 1]

**Comment by phyxdown** [comment]
It is resolved. Pull the newest mvn_repo and run install.sh.

**Comment by phyxdown** [comment]
> [ERROR] Failed to execute goal on project xpipe-parent: Could not resolve dependencies for project com.ctrip.framework.xpipe:xpipe-parent:pom:1.2.4: Failed to collect dependencies at com.dianping.cat:cat-client:jar:3.3.18: Failed to read artifact descriptor for com.dianping.cat:cat-client:jar:3.3.18: Could not transfer artifact org.unidal.framework:framework-bom:pom:4.0.0 from/to central (http://repo1.maven.org/maven2): Transfer failed for http://repo1.maven.org/maven2/org/unidal/framework/framework-bom/4.0.0/framework-bom-4.0.0.pom 501 HTTPS Required -> [Help 1]

It is resolved. Pull the newest mvn_repo and run install.sh.
