### ISSUE TITLE
Any plan for English version? Thanks!

### ISSUE THREAD

**Issue by Hongbo-Miao** [ctripcorp/x-pipe#526]
请问有计划出英文版本吗？谢谢！
Any plan for English version? Thanks! 😃

**Comment by NickNYU** [comment]
英文版是指用户手册吗？ @Hongbo-Miao

**Comment by Hongbo-Miao** [comment]
README 和 UI 吧，就是可以让一个团队的外国人看到这个 repo，也可以自己用起来~ 😊

**Comment by phyxdown** [comment]
有需求就有动力。。 @Hongbo-Miao

**Comment by Hongbo-Miao** [comment]
哈 有需求~ 所以才在这里问的

**Comment by wenchaomeng** [comment]
介绍一下用在哪家公司的什么业务场景？
