### ISSUE TITLE
主数据中心master节点状态问题

### ISSUE THREAD

**Issue by Zengfq0127** [ctripcorp/x-pipe#542]
你好, 我在运行master分支1.2.6的xpipe时遇到了问题, 新创建集群, 管理端页面添加redis和keeper后, 主数据中心中指定为master的redis节点role状态没有得到改变, meta也没为主数据中心的sentinel添加新monitor.

**Comment by songyuyuyu** [comment]
能加一下xpipe的qq支持群吗？里面提供一下详细的信息。

**Comment by Zengfq0127** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月8日(周二) 下午2:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ctripcorp/x-pipe] 主数据中心master节点状态问题 (Issue #542)




 
能加一下xpipe的qq支持群吗？里面提供一下详细的信息。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
